### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by ntwcklng** [derhuerst/cli-autocomplete#1]
Hi,

it would be awesome if you publish the new version to NPM with the `Limit` option.

**Comment by derhuerst** [comment]
Glad to ~here~ hear that you use the library! I published `cli-autocomplete@0.4.0`.

**Comment by ntwcklng** [comment]
Thanks 👍 😎
https://github.com/ntwcklng/pokemon-cp-calculator

**Comment by derhuerst** [comment]
Cool!
